vote/urls.py
# Importing the required modules

# The admin module is used to create the admin site for the application
# using the default django admin site module
from django.contrib import admin

# The path module is used to create the url patterns for the application
# to map the urls to the views
from django.urls import path

# The views module is used to import the views from the views.py file
from voteapp import views

# The settings module is used to import the settings from the settings.py file
# to get the media, static files and other settings
from django.conf import settings

# The static module is used to import the static files from the settings.py file
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


# The urlpatterns list is used to store the url patterns for the application
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.homeView, name='home'),
    path('register/', views.registrationView, name='registration'),
    path('accounts/login/', views.loginView, name='login'),
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('logout/', views.logoutView, name='logout'),
    path('position/', views.positionView, name='position'),
    path('candidate/<int:pos>/', views.candidateView, name='candidate'),
    path('candidate/detail/<int:id>/', views.candidateDetailView, name='detail'),
    path('result/', views.resultView, name='result'),
    path('changepass/', views.changePasswordView, name='changepass'),
    path('editprofile/', views.editProfileView, name='editprofile'),
    path('polls/', views.index,name='index'),
    path('details/<int:question_id>/', views.detail, name='details'),
    path('results/<int:question_id>/', views.results, name='results'),
    path('vote/<int:question_id>/', views.vote, name='vote'),
    path('feed/',views.campaign_feed,name='campaign_feed'),
    path('campaign/',views.campaignView,name='campaign'),
    path('upload_file/',views.upload_file,name='campaign')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voteapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Image(models.Model):
      title = models.CharField(max_length=100)
      file_field = models.FileField(upload_to='images/')

      def __str__(self):
        return self.title
        
class CustomUser(AbstractUser):
    class_field = models.CharField(max_length=100)
    sem_field = models.CharField(max_length=100)
    ROLE_CHOICES = (
        (1, 'Users'),
        (2, 'Candidate'),
    )
    role = models.CharField(max_length=2,choices=ROLE_CHOICES, default=1)
    #REQUIRED_FIELDS = ['class_field', 'sem_field','role']


# ------------------ Online Voting System - Models ------------------ #

# The Position model is used to create the position table
class Position(models.Model):

    # The title field is used to store the position title
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title

class Candidate(models.Model):

    name = models.CharField(max_length=100)

    total_vote = models.IntegerField(default=0, editable=False)

    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    image = models.ImageField(verbose_name="Candidate Pic", upload_to='images/')

    def __str__(self):
        return "{} - {}".format(self.name, self.position.title)

class ControlVote(models.Model):

    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    status = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {} - {}".format(self.user, self.position, self.status)

class VotingTimeSlot(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

class Question(models.Model):
    question_text = models.CharField(max_length = 300)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

templates/Password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
{% load widget_tweaks %}
<br>
<br>
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         <h5 class="card-title">Password Change Form</h5>
         <form action="." method="post">
           {% csrf_token %}
           {% for field in form %}
             <div class="form-group">
               {% if field.errors %}
                 {% for error in field.errors %}
                   <ul>
                     <li>{{error}}</li>
                   </ul>
                 {% endfor %}
               {% endif %}
               {{ field.label_tag }}
               {% render_field field class="form-control" %}
               <br>
               {% if field.help_text %}
                 <small class="form-text text-muted">{{field.help_text}}</small>
               {% endif %}
             </div>
           {% endfor %}
           <button type="submit" class="col-md-12 btn btn-primary">Update</button>
         </form>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/add_time_slot.html
<!-- add_time_slot.html -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

<!-- view_time_slots.html -->
<ul>
    {% for time_slot in time_slots %}
        <li>{{ time_slot.start_time }} - {{ time_slot.end_time }}</li>
    {% endfor %}
</ul>

templates/base.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8" />
   <meta
     name="viewport"
     content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
   <link
     href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
     rel="stylesheet"
     integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
     crossorigin="anonymous"
  />
   <script
     src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
     integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
     crossorigin="anonymous"
   ></script>
   <script
     src="https://kit.fontawesome.com/114f8f7e3d.js"
     crossorigin="anonymous"
   ></script>


   <title>{% block title %}{% endblock %}</title>
 </head>
 <body>
   <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <div class="container-fluid">
       <a class="navbar-brand" href="{% url 'home' %}">Campus Voting System</a>
       <button
         class="navbar-toggler"
         type="button"
         data-bs-toggle="collapse"
         data-bs-target="#navbarNavAltMarkup"
         aria-controls="navbarNavAltMarkup"
         aria-expanded="false"
         aria-label="Toggle navigation"
       >
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
         <div class="navbar-nav">
           {% if request.user.is_authenticated %}
           <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
           <a class="nav-link" href="{% url 'editprofile' %}">Edit Profile</a>
           <a class="nav-link" href="{% url 'changepass' %}">Change Password</a>
           <a class="nav-link" href="{% url 'campaign_feed' %}">campaign_feed</a>
           <a class="nav-link" href="{% url 'index' %}">polls</a>
           <a class="nav-link" href="{% url 'logout' %}">Logout</a>
           {% else %}
           <a class="nav-link" href="{% url 'login' %}">Login</a>
           <a class="nav-link" href="{% url 'registration' %}">Register</a>
           {% endif %}
         </div>
       </div>
     </div>
   </nav>
   <div class>{% block content %} {% endblock %}</div>
 </body>
</html>

templates/campaign.html
{% extends "base.html" %}
{% block title %}Campaign{% endblock %}
{% block content %}
<h1 class="text-center">Welcome to Campus voting System</h1>
<h2 class="text-center">Hi,Candidate {{request.user.get_full_name }}</h2>
<section class="hero-section">
 <div class="card-custom">
  
   <div class="">
     
     
        <div class="card  d-flex">
          <div class="card__background" style="background-image: url(https://wallpapercave.com/wp/wp3739046.jpg)"></div>
          <div class="card__content">
            <p class="card__category">Campaign</p>
            <h3 class="card__heading">Click Here To upload</h3>
          </div>
        </div> 
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          
          <!-- Submit button -->
          <input type="submit" value="Upload">
        </form>
        
      </div>
    </div>
    
</section>


<style>
 :root{
   --background-dark: #2d3548;
   --text-light: rgba(231, 231, 231, 0.9);
   --text-lighter: rgba(255, 255, 255, 0.9);
   --spacing-s: 8px;
   --spacing-m: 16px;
   --spacing-l: 24px;
   --spacing-xl: 32px;
   --spacing-xxl: 64px;
   --width-container: 1200px;
 }
 .card-custom{
  width: 200px;
  height: fit-content;
 }
  *{
   border: 0;
   margin: 0;
   padding: 0;
   box-sizing: border-box;
 }
 .form-upload{
  
  position: absolute;
  bottom: 0;
 }
  html{
   height: 100%;
   font-family: 'Montserrat', sans-serif;
   font-size: 14px;
 }
  body{
   height: 100%;
   background: linear-gradient(45deg,#b57bee, #00e3fd);
 }
  .hero-section{
   align-items: flex-start;
   display: flex;
   min-height: 100%;
   justify-content: center;
   padding: var(--spacing-xxl) var(--spacing-l);
 }
  .card-grid{
   display: grid;
   grid-template-columns: repeat(1, 1fr);
   grid-column-gap: var(--spacing-l);
   grid-row-gap: var(--spacing-l);
   max-width: var(--width-container);
   width: 50%;
 }
  @media(min-width: 540px){
   .card-grid{
     grid-template-columns: repeat(2, 1fr);
   }
 }
  @media(min-width: 960px){
   .card-grid{
     grid-template-columns: repeat(2, 1fr);
   }
 }
  .card{
   list-style: none;
   position: relative;
   border-radius: var(--spacing-l);
 }
  .card:before{
   content: '';
   display: block;
   padding-bottom: 150%;
   width: 100%;
 }
  .card__background{
   background-size: cover;
   background-position: center;
   border-radius: var(--spacing-l);
   bottom: 0;
   filter: brightness(0.60) saturate(1.2) contrast(0.85);
   left: 0;
   position: absolute;
   right: 0;
   top: 0;
   transform-origin: center;
   transform: scale(1) translateZ(0);
   transition:
     filter 200ms linear,
     transform 200ms linear;
 }
  .card:hover .card__background{
   transform: scale(1.05) translateZ(0);
 }
  .card-grid:hover > .card:not(:hover) .card__background{
   filter: brightness(0.5) saturate(0) contrast(1.2) blur(20px);
 }
  .card__content{
   left: 0;
   padding: var(--spacing-l);
   position: absolute;
   top: 0;
 }
  .card__category{
   color: var(--text-light);
   font-size: 0.9rem;
   margin-bottom: var(--spacing-s);
   text-transform: uppercase;
 }
  .card__heading{
   color: var(--text-lighter);
   font-size: 1.9rem;
   text-shadow: 2px 2px 20px rgba(0,0,0,0.2);
   line-height: 1.4;
   word-spacing: 100vw;
 }
</style>


{% endblock %}

templates/candidate.html
{% extends "base.html" %}
{% block title %}Candidate{% endblock %}
{% block content %}
{% if messages %}
 {% for message in messages %}
   <div class="alert alert-danger" role="alert">{{ message }}</div>
 {% endfor %}
{% endif %}


<br />
<div class="container-fluid as-full">
 <h3 class="card-title d-flex justify-content-center">
   Available Candidates for the Election of
 </h3>
 <h2 class="card-title d-flex justify-content-center">{{ obj.title }}</h2>
</div>


<br />
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         <form action="" method="POST">
           {% csrf_token %}
           <table class="table table-striped table-hover">
             <thead>
               <tr>
                 <th scope="col">Candidate</th>
                 <th scope="col">Vote</th>
               </tr>
             </thead>
             <tbody>
               {% for candidateID in obj.candidate_set.all %}
               <tr>
                 <td>
                   <a href="{% url 'detail' candidateID.id %}">{{candidateID.name}}</a>
                 </td>
                 <td>
                   <input
                     type="radio"
                     id="id_{{candidateID.id}}"
                     name="{{candidateID.position}}"
                     value="{{candidateID.id}}"
                     class="custom-control-input"
                     required
                  />
                 </td>
               </tr>
               {% empty %}
                 <p>No Candidates Available</p>
               {% endfor %}
             </tbody>
           </table>
           <input
             type="submit"
             class="col-md-12 btn btn-primary"
             value="Vote"
          />
         </form>
       </div>
     </div>
   </div>
 </div>
</div>


<br />
<br />
<br />
<br />
<br />


<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         <a href="{% url 'position' %}" class="col-md-12 btn btn-primary">Go Back</a>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/candidate_detail.html
{% extends "base.html" %}
{% block title %}Candidate Details{% endblock %}
{% block content %}
<br>
<div class="container-fluid as-full">
 <div class="row as-flex d-flex justify-content-center">
   <div class="col-5 align-self-center" >
     <div class="card border-primary mb-3 bg-dark" style="width: 25rem;">
       <div class="card-body">
         <div class="card border-primary mb-3 bg-light" style="width: 23rem;">
           <img src="{{ obj.image.url }}" class="card-img-top" alt="Candidate Image">
           <div class="card-body">
             <table class="table table-striped table-hover">
               <tbody>
                 <tr>
                   <td><b>Name</b></td>
                   <td>{{ obj.name }}</td>
                 </tr>
                 <tr>
                   <td><b>Competing For</b></td>
                   <td>{{ obj.position }}</td>
                 </tr>
               </tbody>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body{
   background: linear-gradient(45deg,#b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<br>
<h1 class="text-center">Welcome to Online Voting System</h1>
<h2 class="text-center">Hi, {{request.user.get_full_name }}</h2>
<section class="hero-section">
 <div class="card-grid">
   <a class="card  d-flex" href="{% url 'position' %}">
     <div class="card__background" style="background-image: url(https://img.freepik.com/free-vector/realistic-vector-icon-ballot-box-made-glass-hand-putting-voting-paper-inside-election-conce_134830-1493.jpg?w=2000)"></div>
     <div class="card__content">
       <p class="card__category">Vote</p>
       <h3 class="card__heading">Click Here To Vote</h3>
     </div>
   </a>
   <a class="card" href="{% url 'result' %}">
     <div class="card__background" style="background-image: url(https://media.istockphoto.com/id/1281075008/vector/success.jpg?s=612x612&w=0&k=20&c=79U0bXwmDlMwkBQ_qyzGItiRtItpXIQJsSKc2UlvQkk=)"></div>
     <div class="card__content">
       <p class="card__category">Result</p>
       <h3 class="card__heading">Click Here To See Result</h3>
     </div>
   </a>
 <div>
</section>


<style>
 :root{
   --background-dark: #2d3548;
   --text-light: rgba(231, 231, 231, 0.9);
   --text-lighter: rgba(255, 255, 255, 0.9);
   --spacing-s: 8px;
   --spacing-m: 16px;
   --spacing-l: 24px;
   --spacing-xl: 32px;
   --spacing-xxl: 64px;
   --width-container: 1200px;
 }
  *{
   border: 0;
   margin: 0;
   padding: 0;
   box-sizing: border-box;
 }
  html{
   height: 100%;
   font-family: 'Montserrat', sans-serif;
   font-size: 14px;
 }
  body{
   height: 100%;
   background: linear-gradient(45deg,#b57bee, #00e3fd);
 }
  .hero-section{
   align-items: flex-start;
   display: flex;
   min-height: 100%;
   justify-content: center;
   padding: var(--spacing-xxl) var(--spacing-l);
 }
  .card-grid{
   display: grid;
   grid-template-columns: repeat(1, 1fr);
   grid-column-gap: var(--spacing-l);
   grid-row-gap: var(--spacing-l);
   max-width: var(--width-container);
   width: 50%;
 }
  @media(min-width: 540px){
   .card-grid{
     grid-template-columns: repeat(2, 1fr);
   }
 }
  @media(min-width: 960px){
   .card-grid{
     grid-template-columns: repeat(2, 1fr);
   }
 }
  .card{
   list-style: none;
   position: relative;
   border-radius: var(--spacing-l);
 }
  .card:before{
   content: '';
   display: block;
   padding-bottom: 150%;
   width: 100%;
 }
  .card__background{
   background-size: cover;
   background-position: center;
   border-radius: var(--spacing-l);
   bottom: 0;
   filter: brightness(0.60) saturate(1.2) contrast(0.85);
   left: 0;
   position: absolute;
   right: 0;
   top: 0;
   transform-origin: center;
   transform: scale(1) translateZ(0);
   transition:
     filter 200ms linear,
     transform 200ms linear;
 }
  .card:hover .card__background{
   transform: scale(1.05) translateZ(0);
 }
  .card-grid:hover > .card:not(:hover) .card__background{
   filter: brightness(0.5) saturate(0) contrast(1.2) blur(20px);
 }
  .card__content{
   left: 0;
   padding: var(--spacing-l);
   position: absolute;
   top: 0;
 }
  .card__category{
   color: var(--text-light);
   font-size: 0.9rem;
   margin-bottom: var(--spacing-s);
   text-transform: uppercase;
 }
  .card__heading{
   color: var(--text-lighter);
   font-size: 1.9rem;
   text-shadow: 2px 2px 20px rgba(0,0,0,0.2);
   line-height: 1.4;
   word-spacing: 100vw;
 }
</style>


{% endblock %}

templates/details.html
{% extends 'base.html' %} {% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'index' %}"
  >Back To Polls</a
>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
  <strong>{{ error_message }}</strong>
</p>

{% endif %}

<form action="{% url 'vote' question.id %}" method="post">
  {% csrf_token %} {% for choice in question.choice_set.all %}
  <div class="form-check">
    <input
      type="radio"
      name="choice"
      class="form-check-input"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
  </div>
  {% endfor %}
  <input
    type="submit"
    value="Vote"
    class="btn btn-success btn-lg btn-block mt-4"
  />
</form>
{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}
{% block title %}Update Profile{% endblock %}
{% block content %}
{% load widget_tweaks %}


<br>
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         {% if note %}
         <h3 class="text text-muted">{{note}}</h3>
         {% endif %}
         <h5 class="card-title d-flex justify-content-center"> Update Profile</h5>
         <form action="" method="POST">
           {% csrf_token %}
             {% for field in form %}
             <div class="form-group">
               {% if field.errors %}
                 {% for error in field.errors %}
                   <ul>
                     <li>{{error}}</li>
                   </ul>
                 {% endfor %}
               {% endif %}
               {{ field.label_tag }}
               {% render_field field class="form-control" %}
               {% if field.help_text %}
               <small class="form-text text-muted">{{field.help_text}}</small>
               <br>
                 {% endif %}
               <br>
             </div>
           {% endfor %}
           <button type="submit" class="col-md-12 btn btn-primary">Update</button>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/feed.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}

<div class="container mt-4">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for poster in posters %}
      <div class="col">
        <div class="card">
          <img src="{{ poster.file_field.url }}" class="card-img-top" alt="{{ poster.title }}">
          <div class="card-body">
            <h5 class="card-title">{{ poster.title }}</h5>
            <!-- You can include more details here if needed -->
            <a href="#" class="btn btn-primary">View Details</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %} 

templates/home.html
{% extends "base.html" %}
{% block title %}Online Voting System{% endblock %}
{% block content %}
<div class="container">
  <div class="jumbotron bg-white">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
       <h1 class="display-4 text-center">Welcome to Campus Voting System</h1>
    <hr class="my-4">
    <div class="d-flex justify-content-center">
      <img src="https://electionbuddy.com/wp-content/uploads/2022/01/Voting-image-6-scaled.jpg" alt="Ballot Box" width="200" height="200">
    </div>
    <hr class="my-4">
    <div class="text-center">
      <p class="lead">This is a simple voting system where you can vote for your favourite candidate.</p>
      <p class="lead">Admin can add candidates and post the election.</p>
      <p class="lead">Users can vote for the candidates.</p>
    </div>
  </div>
</div>

<style>
  body {
    background:url()
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
  .jumbotron {
    padding: 2rem;
    margin-top: 2rem;
    border-radius: 15px;
    box-shadow: 0 0 10px rgba(0,0,0,0.2);
  }
  .jumbotron img {
    border-radius: 50%;
    border: 5px solid #fff;
    box-shadow: 0 0 10px rgba(0,0,0,0.2);
  }
</style>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}


<br>
<br>
<br>
<br>
<br>
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         {% if messages %}
           {% for message in messages %}
             <div class="alert alert-danger d-flex justify-content-center" role="alert">
               {{ message }}
             </div>
           {% endfor %}
         {% endif %}
         <h5 class="card-title d-flex justify-content-center">User Login</h5>
         <form action="." method="POST">
           {% csrf_token %}
             <div class="form-group">
               <label for="id_username">Username:</label>
               <input type="text" name="username" class="form-control" id="id_username" required><i
                 class="iconinput fa fa-user"></i>
             </div>
             <div class="form-group">
               <label for="id_password">Password:</label>
               <input type="password" name="password" class="form-control" id="id_password" required><i
                 class="iconinput fa fa-keyboard"></i>
             </div>
             <div class="form-group">
              <label for="id_role">Role:</label>
              <select id="id_role" name="role" class="form-control">
                  <option value="1">Users</option>
                  <option value="2">Candidate</option>
              </select>
            </div>
           <button type="submit" class="col-md-12 btn btn-primary button">Login</button>
         </form>
       </div>
     </div>
   </div>
 </div>
</div>




<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }


 .as-full {
   width: 100%;
   height: 100%;
 }


 .form-control {
   padding-left: 30px;
   padding-right: 30px;
 }


 .iconinput {
   position: relative;
   z-index: 1;
   left: 10px;
   top: -31px;
   width: 0;
 }
 .button{
  margin-top: 20px;

 }
</style>


{% endblock %}

templates/results.html
{% extends 'base.html' %} {% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>
<div class="q-center">
  <ul class="list-group mb-5-center">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
     <span> {{ choice.choice_text }}</span>
      <span class="badge badge-primary float-right">
        {{ choice.votes }} vote{{choice.votes | pluralize }}</span
      >
    </li>
    {% endfor %}
  </ul>
</div>
  <div class="text-center">
    <a class="btn btn-primary" href="{% url 'index' %}">Back To Polls</a>
  </div>
  <style>
    body {
      background: linear-gradient(45deg, #b57bee, #00e3fd);
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    .q-center{
      width:500px;
      margin:auto;
    }
    .list-group.mb-5 {
      height: 300px; /* Specify height in pixels or another unit */
      width: 1000px; /* Specify width in pixels or another unit */
    }
    .btn-primary {
      background-color: #ff5733; /* Change the background color */
      color: white; /* Change the text color */
      margin-top: 20px; /* Adjust top margin for centering */
    }
    .badge-primary {
      background-color: #ff5733; /* Change the badge background color */
      color: white; /* Change the badge text color */
      margin-right: 60px;
    }
    .list-group-item{
      display:flex;
      justify-content: space-between;
    }

  </style>
  {% endblock %}
</div>